# Generated by Django 3.1.3 on 2020-11-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='civilState',
            new_name='civil_state',
        ),
    ]
